sudo: required

language: generic

os: osx

branches:
  only:
  - travis

cache:
  directories:
  - .autoconf
  - $HOME/UnityDownloads

# run the script to download and install Unity editor
install:
- sudo -E sh ./Scripts/install.sh

# run the script for unit tests and builds
script:
- sudo -E sh ./Scripts/build.sh

# run the script to upload the builds as tarballs
#after_success:
#- sudo -E sh ./Scripts/post_build.sh

# environment variables used in bash scripts
env:
  global:
  - UNITYCI_PROJECT_NAME="UnityProject"
  - UPLOAD_KEYPATH="./Scripts/upload"